version: "3"
services:
       rest-api:
           container_name: rest-api
           image: nodejsimage
           restart: always
           build: .
           ports:
             - "5000:5000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'